import Head from 'next/head';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Listen For The Moment</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Welcome Traveler' message='Our goal is simple, capture a moment in time for y’all' />
      <Slider slides={SliderData} />
      <Instagram />
    </div>
  );
}
